/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Hotel_System;

import java.awt.Color;

/**
 *
 * @author USER
 */
public class Dashboard extends javax.swing.JFrame {

    private StaffInformation staff;

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
        openHome();
    }

    public void setStaff(StaffInformation staff) {
        this.staff = staff;
    }

    public StaffInformation getStaff() {
        return staff;
    }

    private void openHome() {
        Home.setBackground(new Color(238, 238, 238));
        Home.setForeground(new Color(0, 153, 204));
        Booking.setBackground(new Color(77, 121, 192));
        Booking.setForeground(new Color(255, 255, 255));
        Manage.setBackground(new Color(77, 121, 192));
        Manage.setForeground(new Color(255, 255, 255));
        Checkout.setBackground(new Color(77, 121, 192));
        Checkout.setForeground(new Color(255, 255, 255));
        ViewReceipt.setBackground(new Color(77, 121, 192));
        ViewReceipt.setForeground(new Color(255, 255, 255));

        Home home = new Home();
        jDesktopPane1.removeAll();
        jDesktopPane1.add(home).setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        Dashboard = new javax.swing.JPanel();
        LeftPanel = new javax.swing.JPanel();
        Logo = new javax.swing.JLabel();
        Home = new javax.swing.JButton();
        Booking = new javax.swing.JButton();
        Manage = new javax.swing.JButton();
        Checkout = new javax.swing.JButton();
        ViewReceipt = new javax.swing.JButton();
        Logout = new javax.swing.JButton();
        TopPanel = new javax.swing.JPanel();
        dashboardTitle = new javax.swing.JLabel();
        profile = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        Dashboard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LeftPanel.setBackground(new java.awt.Color(77, 121, 192));

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/dashboardLogo.png"))); // NOI18N
        Logo.setText("jLabel1");

        Home.setBackground(new java.awt.Color(77, 121, 192));
        Home.setFont(new java.awt.Font("Segoe UI", 3, 20)); // NOI18N
        Home.setForeground(new java.awt.Color(255, 255, 255));
        Home.setText("          Home");
        Home.setBorder(null);
        Home.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Home.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        Home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                HomeMousePressed(evt);
            }
        });

        Booking.setBackground(new java.awt.Color(77, 121, 192));
        Booking.setFont(new java.awt.Font("Segoe UI", 3, 20)); // NOI18N
        Booking.setForeground(new java.awt.Color(255, 255, 255));
        Booking.setText("          Booking");
        Booking.setBorder(null);
        Booking.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Booking.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        Booking.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BookingMouseClicked(evt);
            }
        });

        Manage.setBackground(new java.awt.Color(77, 121, 192));
        Manage.setFont(new java.awt.Font("Segoe UI", 3, 20)); // NOI18N
        Manage.setForeground(new java.awt.Color(255, 255, 255));
        Manage.setText("          Manage");
        Manage.setBorder(null);
        Manage.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Manage.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        Manage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ManageMouseClicked(evt);
            }
        });

        Checkout.setBackground(new java.awt.Color(77, 121, 192));
        Checkout.setFont(new java.awt.Font("Segoe UI", 3, 20)); // NOI18N
        Checkout.setForeground(new java.awt.Color(255, 255, 255));
        Checkout.setText("          Checkout");
        Checkout.setBorder(null);
        Checkout.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Checkout.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        Checkout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CheckoutMouseClicked(evt);
            }
        });

        ViewReceipt.setBackground(new java.awt.Color(77, 121, 192));
        ViewReceipt.setFont(new java.awt.Font("Segoe UI", 3, 20)); // NOI18N
        ViewReceipt.setForeground(new java.awt.Color(255, 255, 255));
        ViewReceipt.setText("          View Receipt");
        ViewReceipt.setBorder(null);
        ViewReceipt.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ViewReceipt.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        ViewReceipt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ViewReceiptMouseClicked(evt);
            }
        });

        Logout.setBackground(new java.awt.Color(77, 121, 192));
        Logout.setFont(new java.awt.Font("Segoe UI", 3, 20)); // NOI18N
        Logout.setForeground(new java.awt.Color(255, 255, 255));
        Logout.setText("          Logout");
        Logout.setBorder(null);
        Logout.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Logout.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        Logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoutMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout LeftPanelLayout = new javax.swing.GroupLayout(LeftPanel);
        LeftPanel.setLayout(LeftPanelLayout);
        LeftPanelLayout.setHorizontalGroup(
            LeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LeftPanelLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(LeftPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(Home, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(LeftPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(Booking, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(LeftPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(Manage, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(LeftPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(Checkout, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(LeftPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(Logout, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(LeftPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(ViewReceipt, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        LeftPanelLayout.setVerticalGroup(
            LeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LeftPanelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(Logo)
                .addGap(36, 36, 36)
                .addComponent(Home, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(Booking, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(Manage, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(Checkout, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(ViewReceipt, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76)
                .addComponent(Logout, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        Dashboard.add(LeftPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 610));

        TopPanel.setBackground(new java.awt.Color(255, 255, 255));

        dashboardTitle.setBackground(new java.awt.Color(255, 255, 255));
        dashboardTitle.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        dashboardTitle.setForeground(new java.awt.Color(36, 183, 173));
        dashboardTitle.setText("ADMIN DASHBOARD");

        profile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/profileSetup-removebg-preview_30x30.png"))); // NOI18N
        profile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                profileMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout TopPanelLayout = new javax.swing.GroupLayout(TopPanel);
        TopPanel.setLayout(TopPanelLayout);
        TopPanelLayout.setHorizontalGroup(
            TopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TopPanelLayout.createSequentialGroup()
                .addGap(340, 340, 340)
                .addComponent(dashboardTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 227, Short.MAX_VALUE)
                .addComponent(profile)
                .addGap(20, 20, 20))
        );
        TopPanelLayout.setVerticalGroup(
            TopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TopPanelLayout.createSequentialGroup()
                .addGroup(TopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(profile)
                    .addComponent(dashboardTitle))
                .addGap(7, 7, 7))
        );

        Dashboard.add(TopPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 880, 40));

        jDesktopPane1.setBackground(new java.awt.Color(227, 244, 244));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 810, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 570, Short.MAX_VALUE)
        );

        Dashboard.add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, 810, 570));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Dashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Dashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ManageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ManageMouseClicked
        Manage.setBackground(new Color(238, 238, 238));
        Manage.setForeground(new Color(0, 153, 204));
        Booking.setBackground(new Color(77, 121, 192));
        Booking.setForeground(new Color(255, 255, 255));
        Home.setBackground(new Color(77, 121, 192));
        Home.setForeground(new Color(255, 255, 255));
        Checkout.setBackground(new Color(77, 121, 192));
        Checkout.setForeground(new Color(255, 255, 255));
        ViewReceipt.setBackground(new Color(77, 121, 192));
        ViewReceipt.setForeground(new Color(255, 255, 255));

        Manage manage = new Manage();
        jDesktopPane1.removeAll();
        jDesktopPane1.add(manage).setVisible(true);
    }//GEN-LAST:event_ManageMouseClicked

    private void CheckoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CheckoutMouseClicked
        Checkout.setBackground(new Color(238, 238, 238));
        Checkout.setForeground(new Color(0, 153, 204));
        Booking.setBackground(new Color(77, 121, 192));
        Booking.setForeground(new Color(255, 255, 255));
        Home.setBackground(new Color(77, 121, 192));
        Home.setForeground(new Color(255, 255, 255));
        Manage.setBackground(new Color(77, 121, 192));
        Manage.setForeground(new Color(255, 255, 255));
        ViewReceipt.setBackground(new Color(77, 121, 192));
        ViewReceipt.setForeground(new Color(255, 255, 255));

        Checkout checkout = new Checkout();
        jDesktopPane1.removeAll();
        jDesktopPane1.add(checkout).setVisible(true);
    }//GEN-LAST:event_CheckoutMouseClicked

    private void ViewReceiptMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewReceiptMouseClicked
        ViewReceipt.setBackground(new Color(238, 238, 238));
        ViewReceipt.setForeground(new Color(0, 153, 204));
        Booking.setBackground(new Color(77, 121, 192));
        Booking.setForeground(new Color(255, 255, 255));
        Home.setBackground(new Color(77, 121, 192));
        Home.setForeground(new Color(255, 255, 255));
        Manage.setBackground(new Color(77, 121, 192));
        Manage.setForeground(new Color(255, 255, 255));
        Checkout.setBackground(new Color(77, 121, 192));
        Checkout.setForeground(new Color(255, 255, 255));

        viewReceipt view = new viewReceipt();
        jDesktopPane1.removeAll();
        jDesktopPane1.add(view).setVisible(true);
    }//GEN-LAST:event_ViewReceiptMouseClicked

    private void LogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutMouseClicked
        Login login = new Login();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LogoutMouseClicked

    private void BookingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BookingMouseClicked
        Booking.setBackground(new Color(238, 238, 238));
        Booking.setForeground(new Color(0, 153, 204));
        ViewReceipt.setBackground(new Color(77, 121, 192));
        ViewReceipt.setForeground(new Color(255, 255, 255));
        Home.setBackground(new Color(77, 121, 192));
        Home.setForeground(new Color(255, 255, 255));
        Manage.setBackground(new Color(77, 121, 192));
        Manage.setForeground(new Color(255, 255, 255));
        Checkout.setBackground(new Color(77, 121, 192));
        Checkout.setForeground(new Color(255, 255, 255));

        Booking booking = new Booking();
        jDesktopPane1.removeAll();
        jDesktopPane1.add(booking).setVisible(true);
    }//GEN-LAST:event_BookingMouseClicked

    private void HomeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMousePressed
        Home.setBackground(new Color(238, 238, 238));
        Home.setForeground(new Color(0, 153, 204));
        Booking.setBackground(new Color(77, 121, 192));
        Booking.setForeground(new Color(255, 255, 255));
        Manage.setBackground(new Color(77, 121, 192));
        Manage.setForeground(new Color(255, 255, 255));
        Checkout.setBackground(new Color(77, 121, 192));
        Checkout.setForeground(new Color(255, 255, 255));
        ViewReceipt.setBackground(new Color(77, 121, 192));
        ViewReceipt.setForeground(new Color(255, 255, 255));

        Home home = new Home();
        jDesktopPane1.removeAll();
        jDesktopPane1.add(home).setVisible(true);
    }//GEN-LAST:event_HomeMousePressed

    private void profileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileMouseClicked

        Profile profile = new Profile(staff); // Retrieve staff from the Dashboard class
        jDesktopPane1.removeAll();
        jDesktopPane1.add(profile).setVisible(true);
    }//GEN-LAST:event_profileMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Booking;
    private javax.swing.JButton Checkout;
    private javax.swing.JPanel Dashboard;
    private javax.swing.JButton Home;
    private javax.swing.JPanel LeftPanel;
    private javax.swing.JLabel Logo;
    private javax.swing.JButton Logout;
    private javax.swing.JButton Manage;
    private javax.swing.JPanel TopPanel;
    private javax.swing.JButton ViewReceipt;
    private javax.swing.JLabel dashboardTitle;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JLabel profile;
    // End of variables declaration//GEN-END:variables
}
