/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Hotel_System;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.SwingConstants;
import javax.swing.Timer;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author USER
 */
public class Home extends javax.swing.JInternalFrame {

    private JLabel dateLabel;
    private JLabel timeLabel;
    private Timer timer;

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI) this.getUI();
        ui.setNorthPane(null);
        getContentPane().setBackground(new Color(238, 238, 238));
        calculateIncome();

        dateLabel = new JLabel();
        dateLabel.setFont(new Font("Arial", Font.BOLD, 20));
        dateLabel.setHorizontalAlignment(SwingConstants.CENTER);
        dateLabel.setForeground(Color.WHITE);

        updateDate();

        timeLabel = new JLabel();
        timeLabel.setFont(new Font("Arial", Font.BOLD, 16));
        timeLabel.setHorizontalAlignment(SwingConstants.CENTER);
        timeLabel.setForeground(Color.WHITE);
        updateTime();

        roundPanel1.setLayout(new BorderLayout());

        JPanel contentPanel = new JPanel();
        contentPanel.setLayout(new BoxLayout(contentPanel, BoxLayout.Y_AXIS));
        contentPanel.setOpaque(false);

        JLabel welcomeLabel = new JLabel("WELCOME");
        welcomeLabel.setFont(new Font("Showcard Gothic", Font.BOLD, 45));
        welcomeLabel.setForeground(Color.WHITE);
        welcomeLabel.setAlignmentX(Component.CENTER_ALIGNMENT);

        dateLabel.setAlignmentX(Component.CENTER_ALIGNMENT);
        timeLabel.setAlignmentX(Component.CENTER_ALIGNMENT);

        contentPanel.add(Box.createVerticalGlue());
        contentPanel.add(welcomeLabel);
        contentPanel.add(Box.createVerticalStrut(10));
        contentPanel.add(dateLabel);
        contentPanel.add(Box.createVerticalStrut(5));
        contentPanel.add(timeLabel);
        contentPanel.add(Box.createVerticalGlue());

        roundPanel1.add(contentPanel, BorderLayout.CENTER);

        timer = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                updateTime();
            }
        });
        timer.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        incomeMonthlyLabel = new javax.swing.JLabel();
        incomeMonthly = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        annualIncomeLabel = new javax.swing.JLabel();
        annualIncome = new javax.swing.JLabel();
        roundPanel1 = new Hotel_System.RoundPanel();
        customCalendarPanel1 = new Hotel_System.CustomCalendarPanel();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/dashboardIcon2.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 390, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/dashboardIcon1.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 240, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jTextField1.setBackground(new java.awt.Color(51, 204, 0));
        jTextField1.setBorder(null);

        incomeMonthlyLabel.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        incomeMonthlyLabel.setForeground(new java.awt.Color(204, 204, 204));
        incomeMonthlyLabel.setText("Income Monthly");

        incomeMonthly.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        incomeMonthly.setForeground(new java.awt.Color(153, 153, 153));
        incomeMonthly.setText("$ 0");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextField1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(incomeMonthlyLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(incomeMonthly, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(23, 23, 23))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addComponent(incomeMonthly, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(incomeMonthlyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 250, 190, 110));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jTextField2.setEditable(false);
        jTextField2.setBackground(new java.awt.Color(0, 153, 204));
        jTextField2.setBorder(null);

        annualIncomeLabel.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        annualIncomeLabel.setForeground(new java.awt.Color(204, 204, 204));
        annualIncomeLabel.setText("Annual Income");

        annualIncome.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        annualIncome.setForeground(new java.awt.Color(153, 153, 153));
        annualIncome.setText("$ 0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextField2)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(66, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(annualIncome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(annualIncomeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(16, 16, 16))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addComponent(annualIncome, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(annualIncomeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 400, 190, 120));

        roundPanel1.setBackground(new java.awt.Color(102, 204, 255));
        roundPanel1.setRound(35);

        javax.swing.GroupLayout roundPanel1Layout = new javax.swing.GroupLayout(roundPanel1);
        roundPanel1.setLayout(roundPanel1Layout);
        roundPanel1Layout.setHorizontalGroup(
            roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
        );
        roundPanel1Layout.setVerticalGroup(
            roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
        );

        getContentPane().add(roundPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 420, 180));
        getContentPane().add(customCalendarPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 10, 260, 200));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/TIMBERLAND (1).gif"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 510, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void updateDate() {
        SimpleDateFormat dateFormat = new SimpleDateFormat("EEE, MMM dd, yyyy");
        String currentDate = dateFormat.format(new Date());
        dateLabel.setText(currentDate);
    }

    private void updateTime() {
        SimpleDateFormat timeFormat = new SimpleDateFormat("hh:mm:ss a");
        String currentTime = timeFormat.format(new Date());
        timeLabel.setText(currentTime);
    }

    private void calculateIncome() {
        try {
            File file = new File("checkout.txt");
            FileReader fileReader = new FileReader(file);
            BufferedReader bufferedReader = new BufferedReader(fileReader);

            String line;
            double monthlyIncome = 0;
            double annualIncomeValue = 0;

            while ((line = bufferedReader.readLine()) != null) {
                if (line.startsWith("Total Charges: ")) {
                    String totalChargesStr = line.substring(line.indexOf(":") + 1).trim();
                    String numericPart = totalChargesStr.replaceAll("[^\\d.]", "");
                    double totalChargesValue = Double.parseDouble(numericPart);

                    String checkOutDateStr = null;

                    // Find the corresponding Check-Out Date
                    while ((line = bufferedReader.readLine()) != null) {
                        if (line.startsWith("Check-Out Date:")) {
                            checkOutDateStr = line.substring(line.indexOf(":") + 1).trim();
                            break;
                        }
                    }

                    if (checkOutDateStr != null) {
                        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
                        Date checkOutDate = dateFormat.parse(checkOutDateStr);

                        Calendar currentDate = Calendar.getInstance();
                        int currentMonth = currentDate.get(Calendar.MONTH);
                        int currentYear = currentDate.get(Calendar.YEAR);

                        Calendar checkOutCalendar = Calendar.getInstance();
                        checkOutCalendar.setTime(checkOutDate);
                        int checkOutMonth = checkOutCalendar.get(Calendar.MONTH);
                        int checkOutYear = checkOutCalendar.get(Calendar.YEAR);

                        if (checkOutMonth == currentMonth && checkOutYear == currentYear) {
                            monthlyIncome += totalChargesValue;
                        }

                        if (checkOutYear == currentYear) {
                            annualIncomeValue += totalChargesValue;
                        }
                    }
                }
            }

            bufferedReader.close();

            incomeMonthly.setText(String.format("RM %.2f", monthlyIncome));
            annualIncome.setText(String.format("RM %.2f", annualIncomeValue));

        } catch (IOException | java.text.ParseException e) {
            e.printStackTrace();
        }
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel annualIncome;
    private javax.swing.JLabel annualIncomeLabel;
    private Hotel_System.CustomCalendarPanel customCalendarPanel1;
    private javax.swing.JLabel incomeMonthly;
    private javax.swing.JLabel incomeMonthlyLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private Hotel_System.RoundPanel roundPanel1;
    // End of variables declaration//GEN-END:variables
}
