/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Hotel_System;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        backgroundPanel = new javax.swing.JPanel();
        loginBackground = new javax.swing.JLabel();
        loginTitle = new javax.swing.JLabel();
        Username = new javax.swing.JLabel();
        usernameTextField = new javax.swing.JTextField();
        userLine = new javax.swing.JLabel();
        Password = new javax.swing.JLabel();
        showPassButton = new javax.swing.JRadioButton();
        passwordTextField = new javax.swing.JPasswordField();
        passLine = new javax.swing.JLabel();
        Exit = new javax.swing.JLabel();
        adminLogo = new javax.swing.JLabel();
        Login = new javax.swing.JButton();
        signUpLabel = new javax.swing.JLabel();
        forgetPassLabel = new javax.swing.JLabel();

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backgroundPanel.setBackground(new java.awt.Color(36, 183, 173));
        backgroundPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loginBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/loginBackground.jpg"))); // NOI18N
        loginBackground.setText("jLabel2");
        backgroundPanel.add(loginBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, -1));

        loginTitle.setFont(new java.awt.Font("Segoe UI", 3, 40)); // NOI18N
        loginTitle.setForeground(new java.awt.Color(255, 255, 255));
        loginTitle.setText("LOGIN");
        backgroundPanel.add(loginTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(566, 114, 136, 42));

        Username.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        Username.setForeground(new java.awt.Color(255, 255, 255));
        Username.setText("Username");
        backgroundPanel.add(Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 180, 237, -1));

        usernameTextField.setBackground(new java.awt.Color(36, 183, 173));
        usernameTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        usernameTextField.setForeground(new java.awt.Color(255, 255, 255));
        usernameTextField.setBorder(null);
        backgroundPanel.add(usernameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 200, 216, 20));

        userLine.setForeground(new java.awt.Color(255, 255, 255));
        userLine.setText("_________________________________");
        backgroundPanel.add(userLine, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 210, -1, 20));

        Password.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        Password.setForeground(new java.awt.Color(255, 255, 255));
        Password.setText("Password");
        backgroundPanel.add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 250, 237, -1));

        showPassButton.setBackground(new java.awt.Color(36, 183, 173));
        showPassButton.setForeground(new java.awt.Color(255, 255, 255));
        showPassButton.setText("Show Password");
        showPassButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPassButtonActionPerformed(evt);
            }
        });
        backgroundPanel.add(showPassButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 300, -1, 20));

        passwordTextField.setBackground(new java.awt.Color(36, 183, 173));
        passwordTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        passwordTextField.setForeground(new java.awt.Color(255, 255, 255));
        passwordTextField.setBorder(null);
        backgroundPanel.add(passwordTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 270, 190, 20));

        passLine.setForeground(new java.awt.Color(255, 255, 255));
        passLine.setText("_________________________________");
        backgroundPanel.add(passLine, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 280, -1, 20));

        Exit.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Exit.setForeground(new java.awt.Color(255, 255, 255));
        Exit.setText(" X");
        Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitMouseClicked(evt);
            }
        });
        backgroundPanel.add(Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(772, 0, 22, -1));

        adminLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/admin.png"))); // NOI18N
        backgroundPanel.add(adminLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(555, 12, 125, 96));

        Login.setBackground(new java.awt.Color(0, 204, 204));
        Login.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Login.setForeground(new java.awt.Color(255, 255, 255));
        Login.setText("Login");
        Login.setBorder(null);
        Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginActionPerformed(evt);
            }
        });
        backgroundPanel.add(Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 330, 134, 35));

        signUpLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        signUpLabel.setForeground(new java.awt.Color(255, 255, 255));
        signUpLabel.setText("SIGN UP");
        signUpLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signUpLabelMouseClicked(evt);
            }
        });
        backgroundPanel.add(signUpLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 410, -1, -1));

        forgetPassLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        forgetPassLabel.setForeground(new java.awt.Color(255, 255, 255));
        forgetPassLabel.setText("Forget Password ?");
        forgetPassLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                forgetPassLabelMouseClicked(evt);
            }
        });
        backgroundPanel.add(forgetPassLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(562, 380, -1, -1));

        getContentPane().add(backgroundPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_ExitMouseClicked

    private void LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginActionPerformed
        String username = usernameTextField.getText();
        String password = new String(passwordTextField.getPassword());

        StaffInformation staff = null;

        boolean isManager = false;
        boolean isApprovedStaff = false;
        boolean isProcessingStaff = false;

        try {
            BufferedReader reader = new BufferedReader(new FileReader("staff.txt"));
            String line;
            while ((line = reader.readLine()) != null) {
                String[] parts = line.split(";");
                if (parts.length >= 8) {
                    String staffName = parts[0];
                    String role = parts[1];
                    String email = parts[2];
                    String staffPassword = parts[3];
                    String securityQuestion = parts[4];
                    String securityAnswer = parts[5];
                    String address = parts[6];
                    String status = parts[7];

                    if (email.equals(username) && staffPassword.equals(password)) {
                        staff = new StaffInformation(staffName, role, email, staffPassword, securityQuestion, securityAnswer, address, status);
                        staff.setStaffName(staffName);
                        staff.setRole(role);
                        staff.setEmail(email);
                        staff.setStaffPassword(staffPassword);
                        staff.setSecurityQuestion(securityQuestion);
                        staff.setSecurityAnswer(securityAnswer);
                        staff.setAddress(address);
                        staff.setStatus(status);

                        if (role.equals("Manager")) {
                            isManager = true;
                            break;
                        } else if (role.equals("Staff")) {
                            if (status.equals("Approved")) {
                                isApprovedStaff = true;
                                break;
                            } else if (status.equals("Processing")) {
                                isProcessingStaff = true;
                                break;
                            }
                        }
                    }
                }
            }
            reader.close();
        } catch (IOException e) {
            System.out.println("Error reading staff file: " + e.getMessage());
        }

        if (isManager) {
            JOptionPane.showMessageDialog(this, "Login successful! You are a manager.", "Success", JOptionPane.INFORMATION_MESSAGE);
            Admin admin = new Admin();
            admin.setVisible(true);
            this.setVisible(false);
        } else if (isApprovedStaff) {
            JOptionPane.showMessageDialog(this, "Login successful! You are an approved staff.", "Success", JOptionPane.INFORMATION_MESSAGE);
            Dashboard dashboard = new Dashboard();
            dashboard.setStaff(staff);
            dashboard.setVisible(true);
            this.setVisible(false);
        } else if (isProcessingStaff) {
            JOptionPane.showMessageDialog(this, "Please wait for manager approval.", "Processing", JOptionPane.WARNING_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Invalid username or password!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_LoginActionPerformed


    private void forgetPassLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgetPassLabelMouseClicked
        ResetPassword reset = new ResetPassword();
        reset.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_forgetPassLabelMouseClicked

    private void signUpLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signUpLabelMouseClicked
        SignUp signup = new SignUp();
        signup.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_signUpLabelMouseClicked

    private void showPassButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPassButtonActionPerformed
        if (showPassButton.isSelected()) {
            passwordTextField.setEchoChar((char) 0); // Show the password
        } else {
            passwordTextField.setEchoChar('\u25cf'); // Hide the password
    }    }//GEN-LAST:event_showPassButtonActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Exit;
    private javax.swing.JButton Login;
    private javax.swing.JLabel Password;
    private javax.swing.JLabel Username;
    private javax.swing.JLabel adminLogo;
    private javax.swing.JPanel backgroundPanel;
    private javax.swing.JLabel forgetPassLabel;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel loginBackground;
    private javax.swing.JLabel loginTitle;
    private javax.swing.JLabel passLine;
    private javax.swing.JPasswordField passwordTextField;
    private javax.swing.JRadioButton showPassButton;
    private javax.swing.JLabel signUpLabel;
    private javax.swing.JLabel userLine;
    private javax.swing.JTextField usernameTextField;
    // End of variables declaration//GEN-END:variables
}
