/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Hotel_System;

import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class SignUp extends javax.swing.JFrame {

    /**
     * Creates new form SignUp
     */
    public SignUp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        securityquesLabel = new javax.swing.JLabel();
        answerLabel = new javax.swing.JLabel();
        addressLabel = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        emailField = new javax.swing.JTextField();
        passwordField = new javax.swing.JTextField();
        answerField = new javax.swing.JTextField();
        addressField = new javax.swing.JTextField();
        secquesComboBox = new javax.swing.JComboBox<>();
        signUpButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titleLabel.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(0, 153, 255));
        titleLabel.setText("Sign Up");
        getContentPane().add(titleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 19, -1, -1));

        nameLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        nameLabel.setForeground(new java.awt.Color(0, 102, 153));
        nameLabel.setText("Name:");
        getContentPane().add(nameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 87, -1, -1));

        emailLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        emailLabel.setForeground(new java.awt.Color(0, 102, 153));
        emailLabel.setText("Email:");
        getContentPane().add(emailLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 129, -1, -1));

        passwordLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        passwordLabel.setForeground(new java.awt.Color(0, 102, 153));
        passwordLabel.setText("Password:");
        getContentPane().add(passwordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 171, -1, -1));

        securityquesLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        securityquesLabel.setForeground(new java.awt.Color(0, 102, 153));
        securityquesLabel.setText("Security Question:");
        getContentPane().add(securityquesLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 213, -1, -1));

        answerLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        answerLabel.setForeground(new java.awt.Color(0, 102, 153));
        answerLabel.setText("Answer:");
        getContentPane().add(answerLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 255, -1, -1));

        addressLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        addressLabel.setForeground(new java.awt.Color(0, 102, 153));
        addressLabel.setText("Address:");
        getContentPane().add(addressLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 297, -1, -1));
        getContentPane().add(nameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 89, 190, -1));
        getContentPane().add(emailField, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 131, 190, -1));
        getContentPane().add(passwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 173, 190, -1));
        getContentPane().add(answerField, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 257, 190, -1));
        getContentPane().add(addressField, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 299, 190, -1));

        secquesComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "What is the name of your first pet?", "What was your first car?", "What primary school did you attend?", "What secondary school did you attend?", "What is the name of the town where you were born?" }));
        getContentPane().add(secquesComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 215, 190, -1));

        signUpButton.setBackground(new java.awt.Color(0, 153, 204));
        signUpButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        signUpButton.setForeground(new java.awt.Color(255, 255, 255));
        signUpButton.setText("Sign Up");
        signUpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signUpButtonActionPerformed(evt);
            }
        });
        getContentPane().add(signUpButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 360, 87, 32));

        backButton.setBackground(new java.awt.Color(0, 153, 204));
        backButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        backButton.setForeground(new java.awt.Color(255, 255, 255));
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        getContentPane().add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(259, 360, 87, 32));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/signUpBorder.jpg"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void signUpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signUpButtonActionPerformed
// Get the input values from the fields
        String name = nameField.getText();
        String email = emailField.getText();
        String password = passwordField.getText();
        String securityQuestion = (String) secquesComboBox.getSelectedItem();
        String answer = answerField.getText();
        String address = addressField.getText();

        if (name.isEmpty() || email.isEmpty() || password.isEmpty()|| securityQuestion.isEmpty()|| answer.isEmpty()|| address.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter all fields.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        // Create the staff record string
        String staffRecord = name + ";" + "Staff" + ";" + email + ";" + password + ";" + securityQuestion + ";" + answer + ";"
                + address + ";" + "Processing";

        try {
            // Create a FileWriter object to write to the text file
            FileWriter writer = new FileWriter("staff.txt", true);

            // Write the staff record to the file
            writer.write(staffRecord);
            writer.write(System.lineSeparator());

            // Close the writer
            writer.close();

            // Display a success message
            JOptionPane.showMessageDialog(this, "Staff record saved successfully !", "Success",
                    JOptionPane.INFORMATION_MESSAGE);
            Login login = new Login();
            login.setVisible(true);
            this.dispose();

        } catch (IOException e) {
            // Handle any errors that occur during file writing
            JOptionPane.showMessageDialog(null, "Error writing staff record to file: " + e.getMessage(), "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_signUpButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        Login login = new Login();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressField;
    private javax.swing.JLabel addressLabel;
    private javax.swing.JTextField answerField;
    private javax.swing.JLabel answerLabel;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel background;
    private javax.swing.JTextField emailField;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField nameField;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField passwordField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JComboBox<String> secquesComboBox;
    private javax.swing.JLabel securityquesLabel;
    private javax.swing.JButton signUpButton;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
