/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Hotel_System;

import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class Welcome extends javax.swing.JFrame {

    /**
     * Creates new form Welcome
     */
    public Welcome() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundPanel = new javax.swing.JPanel();
        Logo = new javax.swing.JLabel();
        Line = new javax.swing.JLabel();
        Title = new javax.swing.JLabel();
        Loading = new javax.swing.JProgressBar();
        subTitle = new javax.swing.JLabel();
        LoadingLabel = new javax.swing.JLabel();
        LoadingValue = new javax.swing.JLabel();
        backgroundImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        backgroundPanel.setBackground(new java.awt.Color(101, 215, 205));
        backgroundPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logo.png"))); // NOI18N
        backgroundPanel.add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, 300, 200));

        Line.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/line.png"))); // NOI18N
        backgroundPanel.add(Line, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 650, 90));

        Title.setFont(new java.awt.Font("Segoe UI", 3, 40)); // NOI18N
        Title.setForeground(new java.awt.Color(2, 88, 111));
        Title.setText("Timberland Hotel");
        backgroundPanel.add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, -1, -1));

        Loading.setForeground(new java.awt.Color(0, 153, 204));
        Loading.setBorder(null);
        backgroundPanel.add(Loading, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 900, 30));

        subTitle.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        subTitle.setForeground(new java.awt.Color(2, 88, 111));
        subTitle.setText("Hotel Management System");
        backgroundPanel.add(subTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 370, -1, -1));

        LoadingLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LoadingLabel.setForeground(new java.awt.Color(33, 137, 167));
        LoadingLabel.setText("Loading.....");
        backgroundPanel.add(LoadingLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 260, 40));

        LoadingValue.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LoadingValue.setForeground(new java.awt.Color(33, 137, 167));
        LoadingValue.setText("0%");
        backgroundPanel.add(LoadingValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 440, 50, 20));

        backgroundImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/welBackground.png"))); // NOI18N
        backgroundImage.setText("jLabel1");
        backgroundImage.setPreferredSize(new java.awt.Dimension(900, 500));
        backgroundPanel.add(backgroundImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
        public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        Welcome wel = new Welcome();
        wel.setVisible(true);

        try {
            for (int i = 0; i <= 100; i++) {
                Thread.sleep(20);
                wel.LoadingValue.setText(i + "%");

                if (i == 10) {
                    wel.LoadingLabel.setText("Turning On Modules...");
                }
                if (i == 20) {
                    wel.LoadingLabel.setText("Loading Modules...");
                }
                if (i == 50) {
                    wel.LoadingLabel.setText("Connecting To Database...");
                }
                if (i == 70) {
                    wel.LoadingLabel.setText("Connection Successful...");
                }
                if (i == 80) {
                    wel.LoadingLabel.setText("Launching Application...");
                }
                wel.Loading.setValue(i);
                
                if (i == 100){
                    Login login = new Login();
                    login.setVisible(true);
                    wel.dispose();
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Line;
    private javax.swing.JProgressBar Loading;
    private javax.swing.JLabel LoadingLabel;
    private javax.swing.JLabel LoadingValue;
    private javax.swing.JLabel Logo;
    private javax.swing.JLabel Title;
    private javax.swing.JLabel backgroundImage;
    private javax.swing.JPanel backgroundPanel;
    private javax.swing.JLabel subTitle;
    // End of variables declaration//GEN-END:variables
}
